global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    basic_auth:
      username: "prometheus"
      password: "secret"
    scheme: http
    static_configs:
      - targets: ['servidor1:9100']
        labels:
          environment: production
      - targets: ['servidor2:9100']
        labels:
          environment: production
      - targets: ['servidor3:9100']
        labels:
          environment: production
      - targets: ['servidor4:9100']
        labels:
          environment: production
